### PR TITLE
only ASCII or UTF16 should be used in binary plist

### PR DESCRIPTION
**Pull request by bobrnor**
http://fileformats.archiveteam.org/wiki/Property_List/Binary

### CODE REVIEW

**Comment by DHowett** [comment]
Oh, this is excellent. Thanks!

Would you be willing to add a bplist encoding test for this? I'd like to
make sure that ISO-8859-1 strings get promoted to UTF-16.

**Comment by bobrnor** [comment]
Sure, soon.

**Comment by bobrnor** [comment]
Done.

**Comment by DHowett** [comment]
Thanks, @bobrnor!

**Pull request merged**
